sload bpmn.maude 
---- bpmn.maude is the name of the file in which the BPMN-SEM module is defined. 
---- bpmn-no-msgs.maude  is the name of the file with the spec without messages/events

load time

mod BPMN-EX is

	pr BPMN-SEM . ---- module with the semantics of BPMN

	op o : -> Oid .
	op PROCESS : -> Object .
	eq PROCESS 
    = < o : Process | 
        nodes: (start(id("00"), id("01")),
                task(id("02"), "Cancel order", id("01"), id("03"), 2, id("clerk")),
                end(id("04"), id("03"))), 
        flows: (flow(id("01"), 2),
                flow(id("03"), 2)),
        gtime: 0,
        tokens: token(id("00"), 0),
        resources: (resource(id("clerk"), 1, 1)) > .
endm

search PROCESS =>! < o : Process | Atts:AttributeSet > .
---search [3, 20] PROCESS =>* < o : Process | token(id("03"), 0), resources: (resource(id("clerk"), 1, 1)), Atts:AttributeSet > .